dmtrKovalenko/date-io

__tests__/calculations.test.ts, packages/luxon/src/luxon-utils.ts
- fixes https://github.com/dmtrKovalenko/material-ui-pickers/issues/870
disclaimer: I didn't really look at the pickers code yet. Wondering if it makes more sense to prevent the isEqual(null, sth) check somewhere in the code over there. Anyhow, it shouldn't fail
=> fix isEqual in luxon utils

__tests__/localization.test.ts, packages/luxon/src/luxon-utils.ts
Hi, I have created simple pull request for [raised issue](https://github.com/dmtrKovalenko/date-io/issues/31). I don't find rules or conventions on PR format, so created it this way.
=> Update luxon formats to correct standalone and format versions (!31)

README.md, __tests__/calculations.test.ts, __tests__/localization.test.ts, packages/core/IUtils.d.ts, packages/date-fns/src/date-fns-utils.ts, packages/dayjs/src/dayjs-utils.ts, packages/luxon/src/luxon-utils.ts, packages/moment/src/moment-utils.ts
Returns user-readable format taking into account localized format tokens. Useful to render helper text for input (e.g. placeholder). For luxon always returns an empty string.
=> Introduce new getFormatHelperText method

__tests__/localization.test.ts, packages/date-fns/src/date-fns-utils.ts
One thing that I'm not totally clear about is why my local prettier is creating changes that are different from yours, but the only real change is the adding the tests and then passing locale through those two functions
=> make startOfWeek and endOfWeek locale aware

packages/moment/src/moment-utils.ts
`MomentUtils.formatByString` takes the `date` param and changes it by setting a locale.
Everywhere else in the file `clone` is used but not here. So it's an unexpected mutation of a passed param and it blows up if `date` is frozen.
The only changes are in the `formatByString`, the rest was applied by husky on commit.
=> Fix mutation of date param in MomentUtils.formatByString

__tests__/localization.test.ts, packages/benchmark/operations/calculations.js, packages/benchmark/operations/formats.js, packages/benchmark/operations/parse.js, packages/benchmark/run.js, packages/core/dev-utils.js, packages/date-fns/rollup.config.js, packages/dayjs/rollup.config.js, packages/dayjs/src/dayjs-utils.ts, packages/hijri/rollup.config.js, packages/hijri/src/hijri-utils.ts, packages/jalaali/rollup.config.js, packages/jalaali/src/jalaali-utils.ts, packages/luxon/rollup.config.js, packages/luxon/src/luxon-utils.ts, packages/moment/rollup.config.js, packages/moment/src/moment-utils.ts
This makes sure that locale gets passed through to parse in Luxon and moment
=> fix: correctly handle locale in parse

packages/core/IUtils.d.ts, packages/date-fns-jalali/src/date-fns-jalali-utils.ts, packages/date-fns/src/date-fns-utils.ts, packages/dayjs/src/dayjs-utils.ts, packages/hijri/src/hijri-utils.ts, packages/jalaali/src/jalaali-utils.ts, packages/luxon/src/luxon-utils.ts, packages/moment/src/moment-utils.ts
Add new `lib` property to the adapter in order to make possible to `/disable/add` some functionality based on the adapter. 
```tsx
class Adapter { 
public string: string;
}
```
=> Add `lib` name to the adapter interface

__tests__/localization.test.ts, packages/moment/src/moment-utils.ts
=> getMeridiemText() from moment utils now returns translated text

packages/date-fns-jalali/src/date-fns-jalali-utils.ts, packages/date-fns/src/date-fns-utils.ts
for DST, safari has a bug that caused users to see multiple "20th march 2020" for `date-fns` utils or «1399 فروردین 1» for `date-fns-jalali` utils.
related [StackOverflow question][q]
[q]: https://stackoverflow.com/questions/14839244/why-is-safari-confused-about-date-getday-for-dst-start-in-sydney-aus-time-zon
=> Fix DST bug in safari

__tests__/date-fns-jalali.test.ts, packages/date-fns-jalali/package.json, packages/date-fns-jalali/src/date-fns-jalali-utils.ts, yarn.lock
- update `date-fns-jalali@v2.19.0-2`
- using new `fa-IR` locale (introduced in [v2.19.0-2]) instead of `fa-jalali-IR`
- replace `date-fns` imports with `date-fns-jalali`
[v2.19.0-2]: https://github.com/smmoosavi/date-fns-jalali/releases/tag/v2.19.0-2
=> update date-fns-jalali dependency

packages/core/IUtils.d.ts
This change gives you an advantage when developing with date-io.
If you extend the type as shown below in a project using date-io, you can set the Opaque type so that the Date value is not directly referenced.
```ts
declare module '@date-io/core' {
type Opaque<K, T> = T & { __TYPE__: K };
interface ExtendableDateType extends Opaque<'DateType', unknown> {}
}
```
This allows me to take advantage of TypeScript more powerfully by not dealing with the `any` type.
=> Change `TDate` to an extendable type

packages/luxon/src/luxon-utils.ts
The code for the adders is rather complicated, unnecessary and it will also impact performance on massive calculations.
With simple math, if we add a negative number, it will be subtracted like `10 + -5 = 5`, same goes for Luxon `DateTime.plus`, we can subtract negative values by simple adding them like `DateTime.now().plus({ days: -2 })` and it will subtract 2 days.
Here is a sandbox that demonstrates this https://stackblitz.com/edit/luxon-react-tuw2ft?file=index.js
I made this PR to change all adders from this:
```ts
public addWeeks = (date: DateTime, count: number) => {
return count < 0
? date.minus({ weeks: Math.abs(count) })
: date.plus({ weeks: count });
};
```
into this:
```ts
public addWeeks = (date: DateTime, count: number) => {
return date.plus({ weeks: count });
};
```
=> Simplify Luxom adders

packages/dayjs/src/dayjs-utils.ts
As shown at https://github.com/mui/material-ui/issues/30886 and https://github.com/mui/material-ui/issues/29838, there is a problem validating dates using dayjs.
I noticed that the [parse](https://github.com/dmtrKovalenko/date-io/blob/dc9a2ba540f6032fab5d40d57ba646d8d25e33ba/packages/dayjs/src/dayjs-utils.ts#L108) function uses dayjs parse without strict format, causing dayjs to convert any date, even if incorrect, e.g. "99/99/2000" to a correct date, and due to this, all other functions used later ([date](https://github.com/dmtrKovalenko/date-io/blob/dc9a2ba540f6032fab5d40d57ba646d8d25e33ba/packages/dayjs/src/dayjs-utils.ts#L116), [isValid](https://github.com/dmtrKovalenko/date-io/blob/dc9a2ba540f6032fab5d40d57ba646d8d25e33ba/packages/dayjs/src/dayjs-utils.ts#L128), etc) do not have …
=> Fix incorrect date validation from dayjs

README.md, __tests__/calculations.test.ts, __tests__/date-fns-jalali.test.ts, __tests__/hijri.test.ts, __tests__/jalaali.test.ts, __tests__/local-date-calculations.test.ts, packages/core/IUtils.d.ts, packages/core/dev-utils.js, packages/date-fns-jalali/src/date-fns-jalali-utils.ts, packages/date-fns/src/date-fns-utils.ts, packages/dayjs/src/dayjs-utils.ts, packages/hijri/src/hijri-utils.ts, packages/jalaali/src/jalaali-utils.ts, packages/js-joda/src/js-joda-utils.ts, packages/js-joda/type/index.d.ts, packages/luxon/src/luxon-utils.ts, packages/moment/src/moment-utils.ts
Add two new methods `startOfYear` and `endOfYear` following the model of the other `startOfXXX` / `endOfXXX`.
They will be used on `@mui/x-date-pickers` to improve the behavior when we select a year but the current date is disabled.
For instance if we are on 2018-01-01 and all days are enabled except 2019-01-01 to 2019-01-04.
If we change the year from 2018 to 2019, we expect the new date to be 2019-01-04.
But right now, it will be 2018-12-31 because we don't limit to the current year when looking for the closest enabled date.
This new method will allow to easily create the minDate / maxDate when looking for the closest valid date.
With @alexfauquette we now maintain the date pickers from MUI.
I will probably have other methods to add (`getDate` to get the date number in the month would …
=> feat: New methods `startOfYear` and `endOfYear`

packages/dayjs/src/dayjs-utils.ts
Follow up on #614 
`dayjs` is immutable out of the box, we don't need to clone the date before calling `add` / `substract` / `endOf` / `startOf` or `set`
=> Remove useless date clone in dayjs adapter

README.md, __tests__/calculations.test.ts, __tests__/date-fns-jalali.test.ts, __tests__/hijri.test.ts, __tests__/jalaali.test.ts, __tests__/local-date-calculations.test.ts, packages/core/IUtils.d.ts, packages/date-fns-jalali/src/date-fns-jalali-utils.ts, packages/date-fns/src/date-fns-utils.ts, packages/dayjs/src/dayjs-utils.ts, packages/hijri/src/hijri-utils.ts, packages/jalaali/src/jalaali-utils.ts, packages/js-joda/src/js-joda-utils.ts, packages/luxon/src/luxon-utils.ts, packages/moment/src/moment-utils.ts
Alternative names: `getDayInMonth` / `setDayInMonth` (can be confusing with `getDaysInMonth`)
=> feat: new methods `setDate` / `getDate`

packages/js-joda/src/js-joda-utils.ts
mergeDateAndTime will error out if `time` does not have time components. Most consumers of date-io are unfamiliar that a time library could protect against an issue like that. For instance https://mui.com/x/react-date-pickers/date-picker/ will call mergeDateAndTime when just dealing with dates. This patch will make date-io work more like the other date libraries without a strong type system.
=> do not error when second argument does not have a time part

packages/moment/src/moment-utils.ts
Related to https://github.com/mui/mui-x/pull/6547
When importing multiple locales, the default moment local is the last one.
The `adapter.getFormatHelperText()` will apply the default moment locale instead of the one provided to the adapter.
Fixed by
```diff
-this.moment.localeData()
+this.moment.localeData(this.getCurrentLocaleCode())
```
=> moment: use this.locale when specified

packages/luxon/package.json, yarn.lock
Luxon 3.x has a very minor [breaking change](https://moment.github.io/luxon/#/upgrading) that doesn't affect the shape of the API, so it should be safe for date-io to support it.
=> Add peer dependency support for Luxon 3

packages/core/dev-utils.js
Fixes #248 
As discussed in the issue, `tslib` (Class extending) usage in transpiled code is redundant nowadays as all the major browsers do support ES6, which has native classes support.
The concern with the `opera mini` in the MUI context is somewhat irrelevant as it was discussed and uncovered that it's basically an error on the MUI side and should be removed as [babel ignores it anyways](https://github.com/babel/babel/issues/8545).
**P.S.**: Do note that technically this should be a major bump to signal users, that the new release requires an environment supporting at least ES6.
=> refactor: change build to target `ES6`

.github/workflows/build.yml, __tests__/calculations.test.ts, __tests__/date-fns-jalali.test.ts, packages/core/IUtils.d.ts, packages/date-fns-jalali/src/date-fns-jalali-utils.ts, packages/date-fns/src/date-fns-utils.ts, packages/dayjs/src/dayjs-utils.ts, packages/js-joda/src/js-joda-utils.ts, packages/luxon/src/luxon-utils.ts, packages/moment/src/moment-utils.ts
=> feat: isBeforeMonth and isAfterMonth

packages/luxon/src/luxon-utils.ts
The usage of `DateTime.isDateTime` should be more stable without breaking existing behavior. It also satisfies the current version constraints of luxon (added in 1.6.0).
=> feat(luxon): Use `DateTime.isDateTime` instead of `instanceof`

__tests__/js-joda.test.ts, packages/js-joda/src/js-joda-utils.ts
See https://github.com/mui/mui-x/issues/4703#issuecomment-1192821687 (although note that mui-x no longer uses date-io).
=> fix(js-jods): Propert support for date-only and time-only in mergeDateAndTime method

packages/date-fns-jalali/type/index.d.ts, packages/date-fns/src/index.ts, packages/date-fns/type/index.d.ts, packages/dayjs/src/index.ts, packages/dayjs/type/index.d.ts, packages/hijri/type/index.d.ts, packages/jalaali/type/index.d.ts, packages/js-joda/src/index.ts, packages/js-joda/type/index.d.ts, packages/luxon/src/index.ts, packages/luxon/type/index.d.ts, packages/moment/src/index.ts, packages/moment/type/index.d.ts
closes #372
BREAKING CHANGE: removes the unused with a modern typescript type declaration
=> feat: Remove date-io/type definition

__tests__/jalaali.test.ts, packages/jalaali/src/jalaali-utils.ts
Modified setMonth method to works with jalali month value
=> fix(moment-jalaali): setMonth behavior

__tests__/jalaali.test.ts, packages/jalaali/src/jalaali-utils.ts
current adapter in `jalaali-utils` returns Gregorian number of days in month, leading to problems with [MUI Datepickers](https://mui.com/x/react-date-pickers) about rendering months.
This pull requests fixes the issue and adds missing overrides in jalaali adapter.
=> fix: update jalaali-utils getDaysInMonth and add missing overrides
